### ISSUE TITLE
Slow SQL Statements

### ISSUE THREAD

**Issue by AdmirilRed** [AdmirilRed/RedLibrary#2]
SQL statements going over the internet are inherently slow. Currently, all of the SQL statements are being executed in the thread they are called in, which is hogging the run time of the thread. If there was a runnable that was invoked in a new thread, then SQL statements would not clog up the runtime while they are waiting for a response. Additionally, look into executing statements in bulk rather than one by one when initializing the user interface.

**Comment by richeyh** [comment]
So this is why an app should hit an API that makes the calls rather than direct DB connection also have you tested upload/download speeds from the server? Might be a ISP issue

**Comment by AdmirilRed** [comment]
Version 2.0 will begin using Hibernate ORM. There are definitely speed issues with the server, and I am looking into getting a host from the school.

**Comment by richeyh** [comment]
You should be able to utilize the free tier of AWS for something like this and never be charged a dime. If you need help getting that set up just let me know.

**Comment by AdmirilRed** [comment]
- Moved MySQL server onto RDS (AWS)

- Optimized Hibernate config to no longer check for schema updates because it was a lengthy process with little benefit. This cut down on initial loading time dramatically.

- Changed POJO fetch type to eager. I decided that a marginally longer load time was better than constant transactions. Will need to ensure persistence, however.
