### ISSUE TITLE
Potential Git upgrade 

### ISSUE THREAD

**Issue by richeyh** [AdmirilRed/RedLibrary#3]
Might want to turn Travis on for the Repo and write a few unit tests. 
http://docs.travis-ci.com/user/getting-started/
Really sweet tool that runs checks every time you commit so you can see if you break something. 

I would look into J-Unit for testing java code
https://github.com/junit-team/junit/wiki/Getting-started

It would go into a /tests directory out your application. 

None of this is necessity just best practices that are good to start early. 
Don't feel bad I still forget tests in some projects. It just helps if you have the core functionality tested so when you implement something new you can see the impact / potential bugs.

**Comment by AdmirilRed** [comment]
Included J-Unit plugin with latest version. Have been doing tests to ensure password hashing and salting is giving accurate responses.
